theme: jekyll-theme-slate
title: XAI project - Saliency methods
description: A short blog post about the saliency explainability methods for the summer semester 2022 course on explainables for AI by Michael Stroh
baseurl: /IthronMinya.github.io